# Generated by Django 5.0 on 2023-12-11 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('street', models.CharField(blank=True, max_length=60, null=True)),
                ('house_no', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
