# Generated by Django 5.0 on 2023-12-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_commentmodel_id_alter_postmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
