# Generated by Django 5.0 on 2023-12-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='name',
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
