# Generated by Django 5.0 on 2023-12-15 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0003_remove_cartitems_name_alter_cartitems_price'),
        ('farmers', '0003_remove_items_measure_items_bought_items_measurement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='price',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='item',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='item',
            field=models.ManyToManyField(related_name='add_item', to='farmers.items'),
        ),
    ]
