# Generated by Django 5.0 on 2023-12-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='measure',
        ),
        migrations.AddField(
            model_name='items',
            name='bought',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='items',
            name='measurement',
            field=models.CharField(choices=[('BAG', 'Bag'), ('FARM', 'Farm'), ('BASKET', 'Basket')], default='bag', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='produce',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='items',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
